#!/usr/bin/env python3
"""Generate site/publications.html and the talks list on the personal page
from tools/publications.bib.

Usage: python build_publications.py  (from any directory; paths resolve
relative to this file). Stdlib only; no dependencies.

tools/publications.bib is a synced copy of the canonical CV bib, which
lives in the owner's Tenure workspace. It is never hand-edited here;
publication fixes are made in the canonical file and synced over.

Everything the site needs is carried by the bib entry itself. The script
holds no per-entry key lists, so renaming a bib key cannot silently change
what the site does.

Conventions:
  - \\textbf{...} in an author field marks Kevin; \\uline{...} marks lab
    members. Both render as <strong>. Entries with neither marker are
    support citations and are dropped unless keyworded "include".
  - pubstate sets status: absent means published; "submitted" means under
    review; "inpress" means accepted, not yet out; "rejected" and "hidden"
    drop the entry. Any other value is an error.
  - keywords is a comma-separated routing list. Recognized tokens are in
    KEYWORDS below. Any other token is an error.
  - Entry type sets the section when no routing keyword applies:
    article -> Journal Papers, inproceedings -> Conference Papers,
    incollection -> Book Chapters.
  - award holds honor text shown as a badge on cards and a note in lists.
  - note holds only prose meant to print: free-access links, PMIDs, equal
    contribution footnotes. No status words, no [poster] markers.

The HTML page template at the bottom is site chrome. A chrome edit
(nav, header, footer) must be applied here AND to every page in site/
in the same session.
"""

import datetime
import re
import sys
from pathlib import Path

CURRENT_YEAR = datetime.date.today().year

ROOT = Path(__file__).resolve().parent.parent
BIB = ROOT / "tools" / "publications.bib"
OUT = ROOT / "site" / "publications.html"
TALKS_PAGE = ROOT / "site" / "kevin-lybarger.html"

# Region of the personal page owned by this script.
TALKS_BEGIN = "<!-- TALKS:BEGIN generated by tools/build_publications.py -->"
TALKS_END = "<!-- TALKS:END -->"

# Recognized pubstate values. Absent means published.
STATES = {"submitted", "inpress", "rejected", "hidden"}
DROP_STATES = {"rejected", "hidden"}

# Recognized keywords tokens, and the section each routes to (None means
# the token does something other than pick a section).
KEYWORDS = {
    "selected": None,      # also appears in the Selected Publications cards
    "include": None,       # lab hidden inside "and others"; include anyway
    "talk": None,          # talk, not a publication; see "invited"
    "invited": None,       # with "talk": render on the personal page
    "workshop": None,      # refereed workshop paper; accepted but unrouted
                           # until the display decision lands (decision log,
                           # open item 2026-08-31); entries fall through to
                           # their entry-type section meanwhile
    "poster": "abstracts",
    "abstract": "abstracts",
    "nonrefereed": "nonrefereed",
}

# Sections by entry type, when no routing keyword applies.
TYPE_SECTIONS = {
    "article": "journal",
    "inproceedings": "conference",
    "incollection": "chapters",
}

# Build fails if fewer than this many entries carry a lab-author marker.
# Guards against a CV-side edit stripping the \textbf/\uline convention,
# which would otherwise empty the publications page without an error.
MARKER_FLOOR = 60

# An entry left at "submitted" longer than this is probably stale.
STALE_SUBMITTED_YEARS = 2

LATEX_CHARS = [
    (r'{\"O}', "\u00d6"), (r'{\"o}', "\u00f6"), (r'{\"u}', "\u00fc"),
    (r'{\"a}', "\u00e4"), (r"{\'i}", "\u00ed"), (r"{\'e}", "\u00e9"),
    (r"{\~n}", "\u00f1"), (r"{\'a}", "\u00e1"), (r"{\'o}", "\u00f3"),
    (r"{\'c}", "\u0107"), (r"{\`e}", "\u00e8"), (r'\"O', "\u00d6"),
    (r"\~n", "\u00f1"), (r"\dag", "\u2020"), (r"\&", "&"),
    (r"\%", "%"), (r"~", " "), (r"``", "\u201c"), (r"''", "\u201d"),
]

MONTHS = {"jan": "January", "feb": "February", "mar": "March", "apr": "April",
          "may": "May", "jun": "June", "jul": "July", "aug": "August",
          "sep": "September", "oct": "October", "nov": "November",
          "dec": "December"}


def parse_bib(text):
    """Minimal BibTeX parser for this file's conventions."""
    entries = []
    # Strip full-line comments.
    text = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("%"))
    for m in re.finditer(r"@(\w+)\s*\{", text):
        etype = m.group(1).lower()
        i = m.end()
        depth = 1
        j = i
        while j < len(text) and depth:
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
            j += 1
        body = text[i:j - 1]
        key, _, rest = body.partition(",")
        entries.append({"type": etype, "key": key.strip(),
                        "fields": parse_fields(rest), "order": len(entries)})
    return entries


def parse_fields(body):
    fields = {}
    i = 0
    n = len(body)
    while i < n:
        m = re.compile(r"\s*([\w-]+)\s*=\s*").match(body, i)
        if not m:
            break
        name = m.group(1).lower()
        i = m.end()
        if i >= n:
            break
        c = body[i]
        if c == "{":
            depth = 1
            j = i + 1
            while j < n and depth:
                if body[j] == "{":
                    depth += 1
                elif body[j] == "}":
                    depth -= 1
                j += 1
            val = body[i + 1:j - 1]
            i = j
        elif c == '"':
            # Closing quote counts only at brace depth 0 ({\"O} is content).
            j = i + 1
            depth = 0
            while j < n and not (body[j] == '"' and depth == 0):
                if body[j] == "{":
                    depth += 1
                elif body[j] == "}":
                    depth -= 1
                j += 1
            val = body[i + 1:j]
            i = j + 1
        else:  # bare token (month macro, number)
            m2 = re.compile(r"[^,\s]+").match(body, i)
            val = m2.group(0)
            i = m2.end()
        fields[name] = re.sub(r"\s+", " ", val).strip()
        comma = body.find(",", i)
        if comma == -1:
            break
        i = comma + 1
    return fields


def latex_clean(s):
    for a, b in LATEX_CHARS:
        s = s.replace(a, b)
    s = re.sub(r"\\textsuperscript\{([^}]*)\}", r"\1", s)
    s = re.sub(r"\\(?:emph|textit)\{([^}]*)\}", r"<em>\1</em>", s)
    s = re.sub(r"\\(?:textbf|uline)\{([^}]*)\}", r"<strong>\1</strong>", s)
    s = s.replace("---", "-").replace("--", "-")
    # Strip remaining grouping braces but keep content.
    s = re.sub(r"[{}]", "", s)
    return s.strip()


def esc(s):
    return s.replace("&", "&amp;").replace("<", "[[LT]]").replace(">", "[[GT]]") \
            .replace("[[LT]]", "&lt;").replace("[[GT]]", "&gt;")


def rich(s):
    """Bib field -> HTML, keeping the markup latex_clean generates.

    Escape first, convert second. Escaping after latex_clean would turn the
    <em> it produces from \\emph{} into &lt;em&gt;. Source "\\&" survives
    because esc leaves the backslash and latex_clean maps "\\&" to "&"
    after esc has already produced "&amp;".
    """
    return latex_clean(esc(s))


def link(url, text):
    # Bib URLs carry raw query strings; escape & in the attribute value.
    return f'<a href="{esc(url)}">{text}</a>'


def format_author(raw):
    """One raw bib author -> (html, is_lab_member)."""
    member = "\\textbf{" in raw or "\\uline{" in raw
    s = re.sub(r"\\(?:textbf|uline)\{([^}]*)\}", r"\1", raw)
    s = latex_clean(s)
    if s == "others":
        return ("et al.", False)
    if "," in s:
        last, _, first = s.partition(",")
        name = f"{initials(first.strip())} {last.strip()}".strip()
    else:
        parts = s.split()
        if len(parts) == 1:
            name = s
        else:
            # Keep trailing suffixes (IV, Jr.) with the surname.
            surname = parts[-1]
            k = len(parts) - 1
            if surname in ("IV", "III", "Jr.", "Jr") and len(parts) > 2:
                surname = " ".join(parts[-2:])
                k = len(parts) - 2
            name = f"{initials(' '.join(parts[:k]))} {surname}"
    name = esc(name)
    return (f"<strong>{name}</strong>" if member else name, member)


def initials(given):
    out = []
    for tok in given.split():
        if "\u2020" in tok and len(tok) <= 2:
            out.append(tok)
        elif re.fullmatch(r"[A-Z]\.", tok) or tok in ("et", "al."):
            out.append(tok)
        else:
            dag = "\u2020" if tok.endswith("\u2020") else ""
            out.append(tok[0].upper() + "." + dag)
    return " ".join(out)


def author_list(field):
    raws = re.split(r"\s+and\s+", field.replace("\n", " "))
    names = [format_author(r)[0] for r in raws]
    any_member = any(format_author(r)[1] for r in raws)
    if not names:
        return "", any_member
    if names[-1] == "et al.":
        return ", ".join(names[:-1]) + ", et al.", any_member
    if len(names) == 1:
        return names[0], any_member
    if len(names) == 2:
        return f"{names[0]} and {names[1]}", any_member
    return ", ".join(names[:-1]) + f", and {names[-1]}", any_member


def clean_note(note):
    """Convert links; otherwise print the note as written.

    Status no longer lives in the note (it is in pubstate), so nothing is
    stripped here. Whatever the bib says, the page shows.
    """
    s = note
    s = re.sub(r"\\href\{([^}]*)\}\{([^}]*)\}",
               lambda m: link(m.group(1), latex_clean(m.group(2))), s)
    s = re.sub(r"\\url\{([^}]*)\}", lambda m: link(m.group(1), "link"), s)
    s = latex_clean(s)
    return s.strip(" .,;")


def render(e):
    f = e["fields"]
    authors, _ = author_list(f.get("author", ""))
    title = rich(f.get("title", ""))
    year = re.sub(r"[^0-9]", "", f.get("year", "")) or f.get("year", "")
    sep = " " if authors.endswith(".") else ". "
    bits = [f"{authors}{sep}{title}."] if authors else [f"{title}."]
    t = e["type"]
    if t == "article" and f.get("journal"):
        v = f"<em>{rich(f['journal'])}</em>"
        volnum = f.get("volume", "")
        if f.get("number"):
            volnum += f"({f['number']})"
        if f.get("pages"):
            volnum += f":{latex_clean(f['pages'])}" if volnum else latex_clean(f["pages"])
        seg = f"{v}, {volnum}, {year}." if volnum else f"{v}, {year}."
        bits.append(seg)
    elif t in ("inproceedings", "incollection") and f.get("booktitle"):
        v = f"In <em>{rich(f['booktitle'])}</em>"
        if f.get("pages"):
            v += f", pages {latex_clean(f['pages'])}"
        if t == "incollection" and f.get("publisher"):
            v += f". {esc(f['publisher'])}"
        bits.append(f"{v}, {year}.")
    else:
        bits.append(f"{year}.")
    doi = f.get("doi", "").strip()
    if doi:
        doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", doi)
        bits.append(f'doi: {link("https://doi.org/" + doi, doi)}.')
    note = clean_note(f.get("note", ""))
    if note:
        bits.append(note + ("." if not note.endswith((".", "]", ")")) else ""))
    kw = keywords(e)
    for tag in ("poster", "abstract"):   # label entries inside the mixed section
        if tag in kw:
            bits.append(f"[{tag}]")
            break
    if f.get("award"):
        bits.append(f'<span class="award">{rich(f["award"])}</span>')
    return "<li>" + " ".join(b for b in bits if b) + "</li>"


def venue_line(e):
    f = e["fields"]
    year = re.sub(r"[^0-9]", "", f.get("year", "")) or f.get("year", "")
    if f.get("journal"):
        return f"<em>{rich(f['journal'])}</em>, {year}"
    if f.get("booktitle"):
        return f"<em>{rich(f['booktitle'])}</em>, {year}"
    return year


def render_card(e):
    f = e["fields"]
    authors, _ = author_list(f.get("author", ""))
    title = rich(f.get("title", ""))
    doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", f.get("doi", "").strip())
    url = f"https://doi.org/{doi}" if doi else ""
    if not url:  # fall back to a URL in the note (\url or \href)
        m = re.search(r"\\(?:url|href)\{(https?://[^}]+)\}", f.get("note", ""))
        url = m.group(1) if m else ""
    title_html = (f'<a class="title" href="{url}">{title}</a>'
                  if url else f'<span class="title">{title}</span>')
    badge = (f'<p><span class="award">{rich(f["award"])}</span></p>'
             if f.get("award") else "")
    return (f'<li class="highlight-card">{title_html}'
            f'<p class="card-authors">{authors}</p>'
            f'<p class="venue">{venue_line(e)}</p>{badge}</li>')


def keywords(e):
    """Set of routing tokens on an entry."""
    raw = e["fields"].get("keywords", "")
    return {t.strip().lower() for t in re.split(r"[,;]", raw) if t.strip()}


def pubstate(e):
    return e["fields"].get("pubstate", "").strip().lower()


def has_marker(e):
    a = e["fields"].get("author", "")
    return "\\textbf{" in a or "\\uline{" in a


def validate(entries):
    """Hard-fail on anything the routing rules cannot express."""
    errors = []
    for e in entries:
        ps = pubstate(e)
        if ps and ps not in STATES:
            errors.append(f"{e['key']}: unknown pubstate {ps!r} "
                          f"(expected one of {sorted(STATES)})")
        for t in sorted(keywords(e) - set(KEYWORDS)):
            errors.append(f"{e['key']}: unknown keyword {t!r} "
                          f"(expected one of {sorted(KEYWORDS)})")
        if e["type"] not in TYPE_SECTIONS and e["type"] != "misc":
            errors.append(f"{e['key']}: entry type @{e['type']} has no section")
        if "invited" in keywords(e) and "talk" not in keywords(e):
            errors.append(f"{e['key']}: keyword 'invited' without 'talk'")
        if e["type"] == "misc" and "talk" not in keywords(e):
            errors.append(f"{e['key']}: @misc entry without keyword 'talk'")
    marked = sum(1 for e in entries if has_marker(e))
    if marked < MARKER_FLOOR:
        errors.append(f"only {marked} entries carry a \\textbf/\\uline lab-author "
                      f"marker (floor is {MARKER_FLOOR}); the CV bib may have "
                      f"lost the convention")
    if errors:
        print("BUILD FAILED", file=sys.stderr)
        for msg in errors:
            print("  " + msg, file=sys.stderr)
        raise SystemExit(1)


def classify(e):
    """-> (section, status) for a displayed entry, or (None, reason)."""
    kw = keywords(e)
    ps = pubstate(e)
    if "talk" in kw:
        return None, "talk"
    if ps in DROP_STATES:
        return None, ps
    if not has_marker(e) and "include" not in kw:
        return None, "no lab author marker"
    section = next((KEYWORDS[t] for t in sorted(kw) if KEYWORDS.get(t)), None)
    if section is None:
        section = TYPE_SECTIONS[e["type"]]
    return section, (ps or "published")


def year_key(e):
    y = re.sub(r"[^0-9]", "", e["fields"].get("year", "0"))
    return (-int(y or 0), e["order"])


# Status subsections, in display order. A section shows headings only when
# it holds more than one status.
STATUS_ORDER = [("published", "Published"),
                ("inpress", "In Press"),
                ("submitted", "Under Review")]


def section_html(title, entries, split_status=True, collapsed=False):
    if not entries:
        return ""
    if collapsed:
        out = [f'<details class="pub-collapse"><summary><h2>{title} '
               f'({len(entries)})</h2></summary>']
    else:
        out = [f"<h2>{title}</h2>"]
    if split_status:
        groups = [(label, [e for e in entries if e["_status"] == st])
                  for st, label in STATUS_ORDER]
        groups = [(label, g) for label, g in groups if g]
        for label, group in groups:
            if len(groups) > 1:
                out.append(f"<h3>{label}</h3>")
            out.append('<ol class="pub-list">')
            out += [render(e) for e in sorted(group, key=year_key)]
            out.append("</ol>")
    else:
        out.append('<ol class="pub-list">')
        out += [render(e) for e in sorted(entries, key=year_key)]
        out.append("</ol>")
    if collapsed:
        out.append("</details>")
    return "\n".join(out)


def talk_date(e):
    """Talk entries date either as year+month or as 'Nov. 2022' in year."""
    f = e["fields"]
    raw_year = f.get("year", "")
    year = re.sub(r"[^0-9]", "", raw_year)
    month = latex_clean(f.get("month", "")).strip(" .")
    if not month:
        m = re.match(r"\s*([A-Za-z]+)\.?\s+\d", raw_year)
        month = m.group(1) if m else ""
    month = MONTHS.get(month[:3].lower(), month)
    return year, month


def talk_sort_key(e):
    year, month = talk_date(e)
    order = [m for m in MONTHS.values()]
    idx = order.index(month) if month in order else -1
    return (-int(year or 0), -idx)


def render_talk(e):
    f = e["fields"]
    year, month = talk_date(e)
    title = rich(f.get("title", ""))
    venue = rich(f.get("howpublished", ""))
    when = f"{month} {year}".strip()
    bits = [f"{title}."]
    if venue:
        bits.append(f"{venue},")
    bits.append(f"{when}.")
    return "<li>" + " ".join(bits) + "</li>"


def write_talks(entries):
    """Replace the generated region on the personal page. Returns a note."""
    talks = [e for e in entries if {"talk", "invited"} <= keywords(e)]
    if not talks:
        return "no entries keyworded 'talk, invited'; personal page left alone"
    page = TALKS_PAGE.read_text(encoding="utf-8")
    if TALKS_BEGIN not in page or TALKS_END not in page:
        raise SystemExit(f"BUILD FAILED\n  {TALKS_PAGE.name} has no "
                         f"{TALKS_BEGIN} / {TALKS_END} region")
    body = "\n".join(['<h2>Invited Talks</h2>', '<ol class="pub-list">']
                     + [render_talk(e) for e in sorted(talks, key=talk_sort_key)]
                     + ["</ol>"])
    start = page.index(TALKS_BEGIN) + len(TALKS_BEGIN)
    end = page.index(TALKS_END)
    updated = page[:start] + "\n" + body + "\n" + page[end:]
    if updated != page:
        TALKS_PAGE.write_text(updated, encoding="utf-8")
    return f"{len(talks)} invited talks -> {TALKS_PAGE.name}"


SECTION_TITLES = [("chapters", "Book Chapters"), ("journal", "Journal Papers"),
                  ("conference", "Conference Papers"),
                  ("nonrefereed", "Non-refereed Papers"),
                  ("abstracts", "Abstracts and Posters")]


def report(sections, excluded, talks_note):
    """What the build did, and why. Read this after a bib sync."""
    print("publications build report")
    print("  " + "-" * 58)
    total = 0
    for key, title in SECTION_TITLES:
        group = sections[key]
        if not group:
            continue
        counts = {}
        for e in group:
            counts[e["_status"]] = counts.get(e["_status"], 0) + 1
        detail = ", ".join(f"{n} {st}" for st, _ in STATUS_ORDER
                           for k2, n in [(st, counts.get(st))] if n)
        print(f"  {title:24s} {len(group):3d}   ({detail})")
        total += len(group)
    print(f"  {'displayed':24s} {total:3d}")
    print("  " + "-" * 58)
    by_reason = {}
    for key, reason in excluded:
        by_reason.setdefault(reason, []).append(key)
    for reason in sorted(by_reason):
        keys = sorted(by_reason[reason])
        print(f"  excluded, {reason}: {len(keys)}")
        for k in keys:
            print(f"      {k}")
    print("  " + "-" * 58)
    print(f"  talks: {talks_note}")
    stale = [e for group in sections.values() for e in group
             if e["_status"] == "submitted"
             and int(re.sub(r"[^0-9]", "", e["fields"].get("year", "0")) or 0)
             and CURRENT_YEAR - int(re.sub(r"[^0-9]", "", e["fields"]["year"]))
             > STALE_SUBMITTED_YEARS]
    for e in stale:
        print(f"  WARNING stale: {e['key']} still 'submitted' "
              f"({e['fields'].get('year')})")


def main():
    entries = parse_bib(BIB.read_text(encoding="utf-8"))
    validate(entries)
    sections = {key: [] for key, _ in SECTION_TITLES}
    excluded = []
    for e in entries:
        section, status = classify(e)
        if section is None:
            excluded.append((e["key"], status))
            continue
        e["_status"] = status
        sections[section].append(e)
    selected = sorted(
        (e for v in sections.values() for e in v
         if "selected" in e["fields"].get("keywords", "").lower()),
        key=year_key)
    highlights = ""
    if selected:
        highlights = ('<h2>Selected Publications</h2>\n<ul class="highlight-grid">\n'
                      + "\n".join(render_card(e) for e in selected) + "\n</ul>")
    body = "\n".join([
        "<h1>Publications</h1>",
        highlights,
        section_html("Book Chapters", sections["chapters"]),
        section_html("Journal Papers", sections["journal"]),
        section_html("Conference Papers", sections["conference"]),
        section_html("Non-refereed Papers", sections["nonrefereed"], False),
        section_html("Abstracts and Posters", sections["abstracts"], False,
                     collapsed=True),
    ])
    OUT.write_text(TEMPLATE.replace("[[BODY]]", body), encoding="utf-8")
    talks_note = write_talks(entries)
    report(sections, excluded, talks_note)


TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Publications - Lybarger Language Lab</title>
<meta name="description" content="Publications of the Lybarger Language Lab at George Mason University: NLP and AI for health, clinical information extraction, and conversational agents.">
<meta property="og:site_name" content="Lybarger Language Lab">
<meta property="og:type" content="website">
<meta property="og:title" content="Publications - Lybarger Language Lab">
<meta property="og:description" content="Publications of the Lybarger Language Lab at George Mason University: NLP and AI for health, clinical information extraction, and conversational agents.">
<meta property="og:url" content="https://www.lybargerlanguagelab.org/publications.html">
<meta property="og:image" content="https://www.lybargerlanguagelab.org/assets/images/social-card.png">
<meta property="og:image:alt" content="Lybarger Language Lab: natural language processing and AI for health, George Mason University">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://www.lybargerlanguagelab.org/publications.html">
<link rel="icon" href="assets/images/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="assets/css/styles.css">
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header">
  <div class="wrap header-inner">
    <a class="brand" href="index.html"><img class="brand-mark" src="assets/images/favicon.svg" alt="">Lybarger <span>Language Lab</span></a>
    <nav aria-label="Main">
      <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="people.html">People</a></li>
        <li><a href="projects.html">Projects</a></li>
        <li><a href="news.html">News</a></li>
        <li><a href="publications.html" aria-current="page">Publications</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </nav>
  </div>
</header>
<main id="main" class="wrap">
[[BODY]]
</main>
<footer class="site-footer">
  <div class="wrap">
    <p>Lybarger Language Lab &middot; Department of Information Sciences and Technology &middot; George Mason University</p>
  </div>
</footer>
</body>
</html>
"""

if __name__ == "__main__":
    sys.exit(main())
